<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Yandex Market");
//global $arrFilter; $arrFilter = array("!PROPERTY_WF_SALE" => false);
?> 
<?$APPLICATION->IncludeComponent(
	"webfly:yandex.market", 
	".default", 
	array(
		"IBLOCK_TYPE" => "",
		"IBLOCK_ID_IN" => array(
			0 => "23",
		),
		"IBLOCK_ID_EX" => array(
			0 => "0",
		),
		"IBLOCK_SECTION" => array(
			0 => "0",
		),
		"SITE" => "titansystem.ru",
		"COMPANY" => "Титан Систем",
		"FILTER_NAME" => "arrFilter",
		"MORE_PHOTO" => "MORE_PHOTO",
		"CACHE_TYPE" => "N",
		"CACHE_TIME" => "86400",
		"CACHE_FILTER" => "Y",
		"PRICE_CODE" => array(
			0 => "Розница",
		),
		"IBLOCK_ORDER" => "Y",
		"CURRENCY" => "RUR",
		"LOCAL_DELIVERY_COST" => "500",
		"COMPONENT_TEMPLATE" => ".default",
		"BIG_CATALOG_PROP" => "800",
		"AGENT_CHECK" => "Y",
		"IBLOCK_TYPE_LIST" => array(
			0 => "1c_catalog",
		),
		"SAVE_IN_FILE" => "Y",
		"IBLOCK_CATALOG" => "Y",
		"DONT_USE_SKU" => "N",
		"CATEGORY_NAME_PROPERTY" => "",
		"DO_NOT_INCLUDE_SUBSECTIONS" => "N",
		"IBLOCK_AS_CATEGORY" => "Y",
		"ECHO_ADMIN_INFO" => "N",
		"HTTPS_CHECK" => "Y",
		"USE_SITE" => "N",
		"FILTER_NAME_SKU" => "arrFilterSku",
		"GET_OVER_FIELDS_ANONCE" => "N",
		"PHOTO_CHECK" => "Y",
		"URL_PROPERTY_CHECK" => "N",
		"CACHE_NON_MANAGED" => "N",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"SALES_NOTES" => "sales_notes",
		"SALES_NOTES_TEXT" => "",
		"SKU_NAME" => "SKU_NAME",
		"SKU_PROPERTY" => "PROPERTY_CML2_LINK",
		"OLD_PRICE" => "Y",
		"DONT_CHECK_PRICE_RIGHTS" => "N",
		"DISCOUNTS" => "DISCOUNT_API",
		"AVAILABLE_ALGORITHM" => "QUANTITY_ZERO",
		"CURRENCIES_CONVERT" => "NOT_CONVERT",
		"PRICE_ROUND" => "N",
		"MINIMUM_PRICE_ROUND" => "0",
		"TYPE_PRICE_ROUND" => "MATH",
		"ACCURACY_PRICE_ROUND" => "9",
		"DELIVERY_OPTIONS_SHOP_EX" => "",
		"LOCAL_DELIVERY_COST_OFFER" => "0",
		"DELIVERY_OPTIONS_EX" => "",
		"DELIVERY_TO_AVAILABLE" => "N",
		"STORE_OFFER" => "",
		"STORE_PICKUP" => "",
		"STORE_DELIVERY" => "",
		"OUTLETS" => "",
		"BID" => "0",
		"CBID" => "0",
		"FEE" => "0",
		"CPA_SHOP" => "",
		"CPA_OFFERS" => "0",
		"RECOMMENDATION" => "0",
		"NAME_PROP" => "0",
		"NAME_PROP_COMPILE" => "",
		"NAME_CUT" => "",
		"PREFIX_PROP" => "0",
		"AGE_CATEGORY" => "0",
		"AGE_CATEGORY_UNIT" => "year",
		"ADULT_ALL" => "N",
		"ADULT" => "",
		"EXPIRY" => "0",
		"WEIGHT" => "0",
		"DIMENSIONS" => "0",
		"BARCODE" => "0",
		"PARAMS" => array(
		),
		"COND_PARAMS" => array(
		),
		"NO_DESCRIPTION" => "N",
		"PROPDUCT_PROP" => array(
		),
		"OFFER_PROP" => array(
		),
		"DESCRIPTION" => "0",
		"DETAIL_TEXT_PRIORITET" => "Y",
		"DESCRIPTION_XHTML" => "N",
		"UTM_CHECK" => "N",
		"UTM_SOURCE" => "YandexMarket",
		"UTM_CAMPAIGN" => "",
		"UTM_MEDIUM" => "cpc",
		"UTM_TERM" => "",
		"MODEL" => "0",
		"MARKET_CATEGORY_PROP" => "",
		"DEVELOPER" => "",
		"VENDOR_CODE" => "",
		"COUNTRY" => "",
		"MANUFACTURER_WARRANTY" => "",
		"USE_ONLY_PROP_PICTURE" => "N",
		"PURCHASE_PRICE_CODE" => "WF_EMPT"
	),
	false
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
